notifications:
  slack: cuencafinance:Vb7c4Zn7YCpT0wGjOFDwYQUM

language: python

install: make install-test

cache: pip

script:
  - make lint
  - python setup.py test

jobs:
  include:
    - stage: test
      python: 3.6
      before_install:
        - cp env.template .env
        - export $(grep -v '^#' .env | xargs -0)
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
      before_install:
      - cp env.template .env
      - export $(grep -v '^#' .env | xargs -0)
    - stage: code coverage
      python: 3.7
      dist: xenial
      sudo: true
      before_install:
      - cp env.template .env
      - export $(grep -v '^#' .env | xargs -0)
      install:
      - make install-test
      - pip install coveralls
      script:
      - export PYTHONPATH=`pwd`
      - pytest
      - coveralls
    - stage: PyPI Upload
      python: 3.7
      dist: xenial
      sudo: true
      script: echo "Uploading packages to PyPI"
      deploy:
        provider: pypi
        user: cuenca
        password:
          secure: "VWMU62xKkx+uEX3r3/rZAusOX95IrwvfZg/wDrmIUqilZwcUT2CJUhcQpfkDMeVFAI33VXqFEmpZuYIXGSBwLGpi9dzl7Mbu+jW+Hn+e6Au4j9ZosKiXtRAYr78Ii5Nun5m/GG86niUREmqiO3KaGlw5vSOYoD/uqY5T/REJ8STZG62YruuuB8bgXAWL8acSL0VvUQeljVCCiOGcko+vy9rtb5+bRamsNqT92RIesao8jUWSIjNtn+CQ7VK/23VTiqPhxu/s9c7Nt9eEdgeIchO5eZdKKi2AfSng/RL9EkrNUsxqLhQBHa1YXb7zK4v6Og0RlPbG4Niq67TvHpWXwaDEjxrmovfyf4qPKcv4vjG+roILUPG4IO+2UbA6J9VDRh09gQS3fDnzfJUKg4iw8md/NwNNsAcd7Sr1XC0DmkTP8ah+es8VIb5dLsCHAlQrNrbrgZglNWXxnc3sqeCWu5/Zxs9CbUA1jwAm6M13O00f2aZjHkXBFBoO6bTnI64Ju9y3F8jG+3zH3VXthHl6qEQ9IolWlhVwPV7/2cO4qG1FQk+yijRI5gd2f/EoCrSYsXqsHqpM3dhEpWTrcSe/3ns8mwhDa6ho+L+QueCxQa72lkUyrVOkABBsL5MprVdUGnCDexlBTRSqHlVn0KubtncLr8fVRbL4aitXArOyjYY="

        on:
          tags: true
        skip_existing: true
        distributions: sdist bdist_wheel