notifications:
  slack: cuencafinance:Vb7c4Zn7YCpT0wGjOFDwYQUM

language: python

cache: pip

script: make test

jobs:
  include:
    - stage: test
      python: 3.6
      before_install:
        - cp env.template .env
        - export $(grep -v '^#' .env | xargs -0)
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
      before_install:
      - cp env.template .env
      - export $(grep -v '^#' .env | xargs -0)