notifications:
  slack: cuencafinance:Vb7c4Zn7YCpT0wGjOFDwYQUM

language: python

install: make install-test

cache: pip

script:
  - make lint
  - python setup.py test

jobs:
  include:
    - stage: test
      python: 3.6
      before_install:
        - cp env.template .env
        - export $(grep -v '^#' .env | xargs -0)
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
      before_install:
      - cp env.template .env
      - export $(grep -v '^#' .env | xargs -0)
    - stage: code coverage
      python: 3.7
      dist: xenial
      sudo: true
      before_install:
      - cp env.template .env
      - export $(grep -v '^#' .env | xargs -0)
      install:
      - make install-test
      - pip install coveralls
      script:
      - export PYTHONPATH=`pwd`
      - pytest
      - coveralls
    - stage: PyPI Upload
      python: 3.7
      dist: xenial
      sudo: true
      script: echo "Uploading packages to PyPI"
      deploy:
        provider: pypi
        user: cuenca
        password:
          secure: "RO8GFFGDStxcnOqI0h2XnRjT8nd37eSTPxLh36gZUsx8v2WJ6ARvPvuHj3U59FMs6mLIltlvf3568xeM8V4hJ65yvrBEXmnOtD/qlwhM5EJeMjfTKBGWvh6ySJhs7M2BhOAMKiTGEva1ppeSqQrBaGGO8lDF426Us2drU2v5MBdZj+bOVOWGU/WmPh8WZa8TysX4538+zdmWxUd2+rQTSEmV4CFXFijMvOSZRHxnYHyIq2mqXSEHvBETRM34zyjggUsWpT2vZbewoaGk9vCbKZ4MFdBZE+NN0WFrTxJj64RLb1BlNRRybD8fL5SZHErw4065KRHltS4AAcSmLik5kSVsEiQRzxvVBiXO8hkmImMVN8smo34QQoeCyrOyuHcf6RvNutN0M61yKzEbbai2Mp2wUc8WiO6oT3+OQfxGNu4/crtmck7SmqIldwF6jHGHu93x25aX6EBf3vOk3g4EqM0Anq5KgPKAefYY5NgvZZQpQQ6ZjA5TYE2EL3z7YsHv8zabTubozTPsP0noDIuhVjPruG9rYSZrpuGl6mWoNouMKPI3JGhSRiYS3TGLW3VbF4a/BRVUSHsbxBMW+3jA29dvt550sszIRb3Unj9Y4tCnHCBvTf86Smo6XAHQCQv+Wa5IztQ0clv5knSrM3oyN626Xh5cuOof6REE9+AzRMY="

        on:
          tags: true
        skip_existing: true
        distributions: sdist bdist_wheel